kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    clusterName: "neves-cluster"
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            ddTraceVersions:
              java: "1"
              python: "4"
            ddTraceConfigs:
              - name: "DD_PROFILING_ENABLED"
                value: "auto"
              - name: "DD_DATA_STREAMS_ENABLED"
                value: "true"
    logCollection:
      enabled: true
      containerCollectAll: true
    usm:
      enabled: true
    npm:
      enabled: true
    liveProcessCollection:
      enabled: true
