apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-postgres-db
  namespace: {{ $.Values.teamName }}
spec:
  hosts:
  - "neves-db.cb2l3zpriete.ap-northeast-2.rds.amazonaws.com"
  ports:
  - number: 5432
    name: tcp-postgresql
    protocol: TCP
  resolution: DNS

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-gmail-smtp
  namespace: {{ $.Values.teamName }}
spec:
  hosts:
  - "smtp.gmail.com"
  ports:
  - number: 465
    name: tcp-smtp-tls
    protocol: TCP
  resolution: DNS

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-s3
  namespace: {{ $.Values.teamName }}
spec:
  hosts:
  - "ye-test-bucket-065199070014-ap-northeast-2-an.s3.ap-northeast-2.amazonaws.com"
  ports:
  - number: 443
    name: https-s3
    protocol: HTTPS
  - number: 80
    name: http-s3
    protocol: HTTP
  resolution: DNS
