{{ $context := merge (dict "app" $.Values.dbUploadServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBsECO88/kela//kjdAK7PcVS3dQM1Q724ARrCYRRC+lY/g0qxvjczJNIe5AZ6CuIXdD+xeI9eQn2uwjzDkzU5aoVrdgl4Masho9WQpHRJCM35J5bxgHCXfEvFbSLWwDYi+NTY6QNz0iFoTvQb9jAA4qP4lTeFuvAl/7QIH2rENxricdv7HELZHDuIGKr/RdXgDWJr/ti/qderloOA5cXstO5/Ze310w0X+Pr7E9TWiyOAAEEzM4mHX0tSwzx3PoYYCh33hokTL37z4aA6Qixqc1F0lvSqTzgV3ljVyX8eDUg3DZJqbanzFmG7j04bu8QaW3MbqDFPYyETSs7dAqQ4lUpWVoR4FtkSOqETWsE0Wf1eoVPQeBixgTZKBRPXYiFU5Tmzrbx0y/rjjcp/rz/l5Ch6tyylFwrXXAx1F5K0iFzyE1vodnHqpOj+BP4sQq+F74ZnRye6JgInpE5eYNm6ul7hTyadhyTl3JAnoiWpvnwKM8tl92Q4hYeIPnk7ik6FoGEp8IjWfO/tcOspPqYn9f54Bggr3iZs1awmRcN1C+fQ0nZWH3gC8vPFzLse0SaeBlhjtdra+kWikmfCQ4RJCvEiOVzakN1RCMamwz8xCw/EUqEE3UKM+wIZuq9wGYKGklWI6ZYVoc4ULZ3XN3LlO7jdkFqMBBre/Od3i/Rd9yrLoUIS7sIM05Xr7PoCV7btXRqVnYj2Jcn6R1HxZXEgj/jXnPA==
    AWS_SECRET_ACCESS_KEY: AgCt1/JF2sJ0Hf/P9gyais8RWv4Ix4woVYv3nV2HeyVEXQHQsi3G3yOp0ep/vcR1oS/ruDDTgDOU8sClJ9GWBzz9R3BWiBtbt8RfrEQr3znXDDxp2KpgBX3aAFMaqx8yZrrYPvK0Nfdq74nY8fT/jIz8snwrEHjo/nDyX7sbk95ec9JmdY1wuZ/vn66ERMAWQae7IzL3hlYe7z2XC8+WEKtcQGPSXssRQPY3m1peLQpweRVu52nBcoIMqzYruNVFiaVbml8R0dSGC5+sAo86dLIGcLzBksYlwW5Qcqtf45K+SrlDnCuUhjGxLm5gARaNF2hH3Y/KkM02BKq1KfB4/+3WF/rZbr84AW8nLQByaztWhXfCjvVmc2uQEB9eGGnfsgQKlM+aUCIpUBUwpVSZNCaWlQxl2q6t3iYJX/hcyCZCeUmSLOiMol8EUw5vV+g6Ofpti2RLmIcidgMfCD8jDwHh8ATkQHu2VylsMa9HEJhSvKDvjIkyeQcUdUZtWuH1z5op7M0kLlamH96leqhJru8KCSvd60agJ6M0I35R9rxtlyv/h5nCz/jpKWZEwwGqIrPu88XmJeAL1SStb1/fIW9PEkH0vIEHuA29rAia5VHTWqPQiX6xYWxkUTDXS7V6bMpyLL27jlUWnMmK7PCfnRUWYVQOwz1uLGoZ8EA0iQrf0R3jeRGXWMlNtFf8kL1UrlCIGk6ALSpI6YOFedSehDRZk5Ta7KTfeFP3sr8uLti+uDCRw9ELn2U/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}