apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-slack-webhook-secret
  namespace: {{ .Values.monitoring.namespace }}
spec:
  encryptedData:
    slack_url: AgBiBvaK78zU01MvWfxvRI3NbU4VjriVymND2aKXLU26j8JpBSuQsuEAOy85z4rJ7GTYIm0WaUfyYOowQOgic8YxRPcF9j/j5mOfmOBx+UWq/H2s748X6SA9JPXGE1jEppJdzimNo/Y/eK4Eejz6ta1TkLvNW5pcAmTUWKokiHefrBnlXlrKbcCqD8WYBgAJVBWb4EO5G+rGo+Hg8qeNyx106rSD+qP1gRInvmRnHN1zqjtVOsykxsa1YjaSvlx+ycfokpUBuPm9BxiMLeYW1oF6HosL/P1KDHsKcTMulmIqr0umpCHXIVEIQK4DzXzE/w0d9FYHnV4dW7Vt9jpdXb+3oM5TU1X3yWY1mILOGxkxvYV4/R5yty89DpA+6aj8ViSJnK6cDCZUJWHAAeqUyaZllhnFSToVGVYJGKIxKNPUOiDK5/qhn4VwARd3FvDJLW6rcgGzRqvOdTfSo5efpQq4VZbt/Aj126QykMr7r//SGr2fLzFkjQqPBxT6FkokJDW0IgavmFGN7JGS0Yqf36erDyxp0RcuO3xFKI82ylo5dWGORwgodHNUcu2BuGvlnxvc90CgA3KCyEO/zDYm+FyYDaDZ4+FBTeK2Y3cEj3OtxD1Zyn0DgZWnvfpBSJxDw1mMVwzfBptBHSmKVcxxgC+kRdMcBd3bqUqjSTyJ5JmlI95MBE0eSQ1JI4eoU8U9CIY0xm2vCwgdM6cMWDFnrozQ3VFM40WPNIr3cuI9tZjHrCpYxccWDXkYqTU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-slack-webhook-secret
      namespace: {{ $.Values.teamName }}