{{ $context := merge (dict "app" $.Values.mailServer) . -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    GMAIL_PASSWORD: AgA9DFuvbeO6okYQGtFvVuBwI8qh118BXnEPwnKjGOJYq+8XDjSxkDIHEzuhUp3quJS4eWXc62FW/Rw3UgfQOJnmGLzFS0b/Va63z9W1Hfz5C9KACWX0yyyQatFjteETiKevy37vlOy+TU5E9YjYQz4ToB7Dn4z7l7izr8RHTN972hNXrdIkgeGx2W+/rk7Edz0Po85+iNY1m0e0Cup7a36AWRN4AxM7OpaXoWa738XXZ8ULImiydnfjufHECyyS+XMFcuYg5ap+RzOg7Y6Z6N+Yb3Pe7+efmJZtKBSWUxFRqP/Vby562pTLtnXTnvEgLH/8oQhwAiy57o7EudBKCThHWHKhx6hx23xJ17pstY84PN2b47nTi8Zu2RLLYdCcgz6Nm4MmBovK0sLCXF55j0dZHuUBHiSyFPg/xarwK8MvYzTR+FkGEj598KJxncs8M+grdGeosGkpTyExG/vTX7/Raq8niYij1VkwMoZnueAFT/5cRuDISdU4APKtzZsOJyPzoVtPxhJ3dAdcGKh+wLzmNAO+GK9luEUpn7bxWzgoV/wAcpyM/jcvPnWkhoLw+WfvOwRgOdQJwclDuWQMi/TjBbYnlY/E8f9DX4Nhq8UbeYBkMp/7lhBgxn071A1Yb5fm3wpIulZoLcHsjOILRTgsitRgvn7WVJ/XMqqt3nFF5iaUEJSx5k++LC4473BQumcaw8IP77o3thSIeKLC1hGq7fnc
    GMAIL_USER: AgA36V4fFIC494aFrCMog5pwwdfiUR+o2GC4mph6IM3fiHAyWGh23j2zzYQKeFN0N5I+hDf2B52AO1J6aubdv+SSgaENcfSFyFSfSzkMqIIacFWTpNcSBysJPXa23HuUtMvy7NTECS4NaPpg58TM5HG1/aUSXFcUdjHBp8vyQOhsjfLljuuJ7K/6W9V+vjowfpgxqdk9PHhPzf6AG3dViS3hA7W1bI0oxw1iPlfPvr41lUsi7f/NOBcfyhsGg9Un/CKoLdh+Vg7FLEexP3ZjZcicc3ynySkZMAFCwfBKxprTzYEO/3mNGl/xV+c+QlUtk+PtgLZFtFRiji/HmpJyNZ568/TReTA+Dhjx+g5o1As9ICaRLqhZZAiEJ9dYGoSgNq5g8XURo4q60t717/UbSNbHrLzCyQMaLAD28HFmbiQ9oj98SLxs1zOI20AtJOcZrxHnLZiOyHDDn/PADaSLlDAlUawad8bbCZBC8KPQPFBXT3zWOzQ21RymisjEYOFU00GhzU9Nk5AOfhFnWxc7sH/vAXUMr/CTYgfie5UKcvmXpXqYNTtKaKLJ/laHt30dQRmpnim3D+V3X8R967S3bkvH6SrMxFSF5NzoVz1MHLUwPL0wDGX1P7alPdXhz/m2Cbjf/2VPue+sxqOq8LBD5lh3VuEcHXTH28UP3dKuLFqLvNC9aJmV/zx2SchdrUYkAilO2qYUAbva07nPuqWhzRu4jj9H8A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}