{{ $context := merge (dict "app" $.Values.playServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    KEY_PAIR_ID: AgAMpGRzbSWYOWomKKjPDXkvRIOF6IfPUasKCl8ZVvAjm+vcKwOUTv+Kf9XapRiwIBeD694mj6Q5hW9AVPa4mKMr2Yg8bYrXV6ZJ2cCyRDqmqtbehivL1NojRptLtcfSPjJ3ApT58oNJm7dTUdsQpdt9MMG/a6sBRifawr2l+3CF7aa0LVOTTfced3XHsWsaKE3OF9v6eiKkLTlKMKIFgVRjlDgXejEpGADkQCYBqJxLL+P09UhxKe4cyjaEzfCGtmYcRT80JXldyROsrrivfM6fPrwKbC0jLHi45e51x1PhY5oeL7VPjH3v2RPY5fVzY/7iE+cquVzkxSHXbxP/ijtEomiG+eGCcgDkCLVzfKqqsFuVgflgwILnuez0IFjJXK6R4CIDMMQMd1sw8GLNb4gcU/G0DXFLLJDsfYIiuHw9hFTIsCSdkqhWkpCKmgxdLBrbKcm12/P/fKHhVaMLfpzEyIGY+u5CNZDdQhoObBw8QkvEOLbm6IG3oTyiQ42IO6MCP25reMwYorg/kp8LIqbmue99oKEWjl+vTo4lOMJk+ZQweGgZEQReDawjPMyFIXqZGpu9hqzHhzUFreHnyqr9/so2aUiD+6pUWBjSyM9h5UDGnNAZMij3+jxRwhfY3CwQtXf/SHjf9OdVln+t9E6FoDN3MxqaBQ4m2EhThWjBIm54H7u/3+A5xQn9oApeD8z0TIEagX1H+w==
    S3_PRIVATE_KEY: AgDxyW1lihj9sdtoSPcFE1VBAQfh4F5bFaauy5Ga8rofgndLU6rVd9vTWyQwHp32tJ48EUJ1T+HU+yRZvmZHIqXAWs54SqROdg/4vDkHJddDPe/kAk7S309yFeIc9q7vPfnl0PxZvtFNggfZ5eMRIGSX/TSJMiS4OBkWET+Va4vF5hdHPFBZLrTSOF8eFhJ9JDWCwJd2lHppqZfV+duCZakcaWO7Ebp/XFSNacTMrLrSuNoCzpFktQRXlYVogGvxq2Mno/T19B1+aALFi1/LHSmIEdMxoCZYPGJSLPhksm2bixew7RdrT0GImC6Po+mI2roW1YIff6tbhbJqz04S0SXdtDhWoE8x+ek6ZPaMSk7g65XCkBIOBu6fIeUDGepfap7v1VmjaLa3uh6la9TehfzbnOwYPeaZKKoUMQkqisUCMKGeY1XoXjnD4UT0Qs4ZvAZNMbdsBSWEZ12BERUbbxlfXhVn/mYV7tO7X4MsaH/cAlp65MgX9bshecVcQDft/99WNaymafE8GKpo+6G5Z5Mwpxgv2GJRSG7uVQDXatJEHPYZjZTG7uK6P+lshdWesYYJkUFmRoV+RHJypofdj9uftF/IMuOrXDUIf2dMvcC8+ZFTPJ6iW4DPwpIOU80fLpurRvZp1PcK8rFwaViuYQiZm8hEhKMhbkmmu6qAhynmEcdxq0Ujn54u/5KqphxGEMY7nLb7GkGZjeF7AwXIi7ayxHU3i8UeUZM9coO2GS5beGTRa9J70+AHYED7sIWhYfQl141pII9qpuC60NSA/VGbQr1+sg8XtUEn7pgDfe+uGsLiEfD6Iy9lSDDPOWKEkp3GyBskxguJVkHIXQ+t7ZsqSa6rWW0RItCUYanVsAHo5gIK2wle1A9LvPFd4vhYwcb1bvUCpejs4gZB
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}