{{ $context := merge (dict "app" $.Values.statusServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    RDB_PASSWORD: AgCeTRSoZ2ocUOoGHAJ5E50EXsU3Q3n7y468UGr5+75OJYHzM5xVuNmD4rv3No/fwReMmiAe0UwIFySyoAm88Xv3D34D3z7VbEBuj6WkYe2fX5TdW6gK77U3cNZSwSO5v+nxf2jmUqFfus3SocdMvXgd7hpx5UaDDlZlGI4V59g54jnBZmrlqL9MhoBQ4ceDveJH5KjbCoWhXCQ1mweLEj9FYjT2nEuAmgk902TLZMqq8H965FbYZ+u0UrchLcOL8/KN5t91nywVjweG4mxEjmVqCWp5SmTM4yEnHPQUNvzS+zPnRBdZSbBYbxCbCdn8D47ece25O6hegvQaz6CBuERX1F3A7WabhogbZhkKH0t0zP6Z3t8jaaAt8TfST40jQ9Qab9jx8muEXfrBbB6fpfTF71rfi/jL4fK5FQ9WgDv4cPgcsnsCR6W8mKNCPdGhPeAsbLFmX6VQAX/4nY/YG83kwLbFW9AeN68f8Y1KYrIpb435Pw6NI1Ui8BUajCI7CgbQqBmxl6KCl5eyfapK5bOh4OoqoAUvmWytvQfX7FjF7xiraz42UpDFYRSy8kCvNDbQC4GI8RjhZt6MWOj64CeVNtn/chFLHf3loJ1HrcSz8Veyr3CW1c8k6tn/3IyLrGUFQzA+x9BU9fJVDNR+xTOf0WC3Z7Rz1fV7YgzHPTYG5uXk1OweYuEGLSXeEtefJGrAIBuxN2Z5cw==
    RDB_USER: AgDDJQx6Rynd4V9jFAHB52GuxDEwr0/hRSqMHxkTRBl8IdZHR6BMrMTkOE9+BDMjsB8/ADWg5FT5Lp0vhoAWYqvvBEkkurhFKPgldMstV10gAJF06HRisz7FHcBDR8GVRinmM5sMyeuG9PUFQ0aMPjeKNMilcDdmKjtKBpQPpsasY97ENptnkEUvMuM0aT+Ndr6cSVinZ+B9nt9JzcwvdCE79Tk6lSyDpMwiEi7KhXWVRHP2oaZwFzzJULgUx/yMDLbb88L9BxhLSwp3a6hL1hG0ry58yBey0ZrS5nKV0KLUfPe5DRj4WK5RN/zy6FauULdXJDFy+mupK2LG4rZxpxF7wq8h5oo/ZuxsfDNR18XGlQMyhBbtR0bbKFZ+4dOGQ0YvI9yWqzs7AtLZn5Em30HGzFnHZm2X+Xg+fuYfhVSxqQ0U4+cjasFa/HkMtktLKeis1Wbyj+EfDXiqZNM1kV5CnuKJEjagrlxXffcL4SpmKng4VqsN3RntUX4xTq0tjHxRuw5NCDENe7P8v63hPWsWE79kmdb/pAtXe92ngZaXFlCMNB1guMEMU6qWgCXpUUlCrCbq92MsYvwzt5jBfuGadqBJgAPBPArUEGlELfYNNI3HTfgAUPEUs8gWKztwveAlKAdA9JSUFd8Jmknctqd+QCpKaGRlNYkqCyJX8FT51AJXzrF90a/IMCNlJA+sjC2xpA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}